name: MSys2 build

on:
  push:
  pull_request:
    paths-ignore:
      - README.md
      - .gitignore
      - LICENSDE

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        msystem: [mingw64]
        mode: [debug, release]

    runs-on: windows-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4
      name: Checkout repository

    # Setup MinGW
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        install: base-devel git unzip p7zip mingw-w64-x86_64-toolchain mingw-w64-x86_64-xmake

    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
      name: Install xmake
    
    - name: Build ${{ matrix.mode }}
      run: |
        xmake f -m ${{ matrix.mode }} --arch=x86_64 --build_tests=y -y
        xmake
    
    - name: Run tests
      if: matrix.mode != 'release'
      run: |
        xmake run FlTests

    - name: Prepare artifacts
      run: |
        mkdir ${{ matrix.mode }}-artifact
        mv bin/mingw_x64_${{ matrix.mode }}/ ${{ matrix.mode }}-artifact/
    
    - uses: actions/upload-artifact@v4
      with:
        name: FlashlightEngine_MSys2_${{ matrix.mode }}_${{ github.run_id }}
        path: ${{ matrix.mode }}-artifact/
      name: Upload debug artifacts
