name: Windows build

on:
  push:
  pull_request:
    paths-ignore:
      - README.md
      - .gitignore
      - LICENSDE

jobs:
  build:
    strategy:
      matrix:
        mode: [debug, release]

    runs-on: windows-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}

    steps:
    - uses: actions/checkout@v4
      name: Checkout repository

    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
      name: Install xmake
    
    - name: Build ${{ matrix.mode }}
      run: |
        xmake f -m ${{ matrix.mode }} --build_tests=y -y
        xmake
    
    - name: Run tests
      if: matrix.mode != 'release'
      run: |
        xmake run FlTests

    - name: Prepare artifacts
      run: |
        mkdir ${{ matrix.mode }}-artifact
        move bin/windows_x64_${{ matrix.mode }}/ $${ matrix.mode }}-artifact/
    
    - uses: actions/upload-artifact@v4
      with:
        name: FlashlightEngine_Windows_${{ matrix.mode }}_${{ github.run_id }}
        path: $${ matrix.mode }}-artifact/
      name: Upload debug artifacts